### ISSUE TITLE
Segmentation Fault when Using an ItemsRepeater in a Scrollviewer

### ISSUE THREAD

**Issue by MorganAbrams** [AvaloniaUI/Avalonia.Controls.ItemsRepeater#11]
**Describe the bug**
On Debian Buster, when you use an ItemsRepeater inside of a ScrollViewer and start to scroll after a little while you get a segmentation fault error. This only occurs when using .net 6.

**To Reproduce**

1. Go to [Example Repository](https://github.com/mabrams17/SegFault-AvaloniaExample)
2. Download and run the code
3. Scroll down until crash (should occur quickly)
4. See error on terminal

**Expected behavior**
Ability to keep scrolling down and view all data without crashing.

**Screenshots**
No screenshots.

**Desktop (please complete the following information):**

- OS: Linux - Debian Buster
- Version 10.11

**Additional context**
Does not occur on windows 10. Using the .net 5 sdk lets the program run normally as expected

**Comment by colejohnson66** [comment]
This was an issue in .NET, not Avalonia, and can be closed.
